logging:
  level:
    graphql: ERROR
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  main:
    lazy-initialization: true

  jpa:
    generateDdl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create-drop
        use_sql_comments: true
        format_sql: true
    show-sql: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '123'
    username: root
    url: jdbc:mysql://localhost:3306/fides?zeroDateTimeBehavior=convertToNull&autoReconnection=true&autoReconnectForPools=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


cloud:
  aws:
    credentials:
      access-key: AKIAYI7RBWHAXEASZIPV
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: my-fides-bucket





jwt:
  secret: ani-jwt-key
  expirationDateInMs: 86400000


